# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9874b8a37b55d182bef61b2a4f6e18128bdb192641ea61d94f0300077fa07c1c7a1e86f3c937d82ae9529ca54020ad08f3411cc7b94c2ea5fc6f1193532ffccc

test:
  secret_key_base: ec6160c2dee8e9c559d4b48c8409aca050ac1405e90e00058418f712b947db516bcac754f4726b4535db03f6d66b2c19d3f2c07e291d2b1dc1de47f82a66adea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
